### ISSUE TITLE
不应该把smartrefresh集成到core模块

### ISSUE THREAD

**Issue by guozhiqiang123** [robin8yeung/BrickUI#1]
如题，smartrefresh太重了，可以单独提供库支持。
core模块应该是一个框架最核心最基础的东西。

**Comment by robin8yeung** [comment]
> 如题，smartrefresh太重了，可以单独提供库支持。 core模块应该是一个框架最核心最基础的东西。

合理，我优化下

**Comment by robin8yeung** [comment]
> 如题，smartrefresh太重了，可以单独提供库支持。 core模块应该是一个框架最核心最基础的东西。

close点错了

**Comment by robin8yeung** [comment]
### 0.2.15

- Improve: `smartRefresh`提到单独module：com.github.robin8yeung.BrickUI:brick-ui-smart-refresh。**（注意：用到smartRefresh的话必须引入此依赖）**
- feature: 添加`Fragment.fragmentPager()`方法，来构造基于Fragment生命周期的fragmentPager
- feature: 统一增加`foreground`属性（系统版本23以上才支持）
- feature: 提供`livePlaceHolder()`构造占位View
