### ISSUE TITLE
能否实现一个TreeList

### ISSUE THREAD

**Issue by ituuyij5693** [robin8yeung/BrickUI#10]
需要这个功能，请老大实现一下

**Comment by robin8yeung** [comment]
TreeList是啥？如果是层级嵌套的列表，可以用多个RecyclerView组合实现，或者用RecyclerView和Column结合来实现。如果已经有现成的自定义View实现了，建议用brick { ... } (即之前的 view { ... })嵌入到BrickUI里

**Comment by ituuyij5693** [comment]
谢谢提示，已用RecyclerView 和 liveColumn 实现！
