### ISSUE TITLE
希望为每个控件提供foreground这个属性的设置

### ISSUE THREAD

**Issue by guozhiqiang123** [robin8yeung/BrickUI#2]
1、如题；
2、我们一般可以在foreground属性上设置点击水波纹效果，所以还希望提供RippleDrawable的封装。

**Comment by robin8yeung** [comment]
已增加foreground，但RippleDrawable没怎么用过，怕封得不好，可以考虑自己封装。BrickUI提供了stateListColor，stateListDrawable这些方法来构造ColorStateList和StateListDrawable

### 0.2.15

- Improve: `smartRefresh`提到单独module：com.github.robin8yeung.BrickUI:brick-ui-smart-refresh。**（注意：用到smartRefresh的话必须引入此依赖）**
- feature: 添加`Fragment.fragmentPager()`方法，来构造基于Fragment生命周期的fragmentPager
- feature: 统一增加`foreground`属性（系统版本23以上才支持）
- feature: 提供`livePlaceHolder()`构造占位View
