### ISSUE TITLE
一点想法

### ISSUE THREAD

**Issue by guozhiqiang123** [robin8yeung/BrickUI#3]
作者还真是给力！
那我就再提一点自己的想法。
现在的动态能力主要依赖LiveData，后期如果换成Flow可以参考https://github.com/airbnb/mavericks  这个库
虽然我还没有具体思路该怎么封装，但是我隐约觉得可以封装出和flutter一样风格的，而且可以做到全属性动态。
现在动态能力还只是个别属性用LiveData包裹，灵活性太差了，而且不利于后期维护。如果能封装成这个库的样子，每一个属性就是data class中的一个变量，内部再去监听，做增量刷新。

**Comment by guozhiqiang123** [comment]
感觉没有那么麻烦了，这位大佬直接给出了方案，我觉得可以直接移植。
https://juejin.cn/post/7025222741322121223

**Comment by robin8yeung** [comment]
看了下这个方案，它主要提供的是面向状态编程，如MVI一类架构的编程范式，其实和BrickUI不是一个层面的东西。

除此以外，在BrickUI上进行面向状态开发也是可以的，推荐的方式是使用seal class来定义状态，用LiveData来承载这个状态，通过map把状态的详情绑定到具体UI上。

最后，想让BrickUI没有封装的View属性也可以有动态能力，可以自行通过LiveData.bind()和LiveData.bindNotNull()来实现，以下0.2.19版本进一步封装，简化了开发者的使用，具体使用示例如下所述。

需要指出的是，Mavericks也需要在invalidate()中实现把更新后的状态详情更新的View上，但我认为这样做并不算特别优雅
- 需要有个字段来引用这个View，初始化这个引用需要用到findVIewById或ViewBinding
- 如果要增加或删除一个View，需要同时修改xml和invalidate()里对这个View的操作

### 0.2.19

- feature: 提供更易调用的`LiveData.bind(context, block)`和`LiveData.bindNotNull(context, block)`方法，方便开发者绑定LiveData到View。
- improve: 优化`LiveData.bind(context, block)`和`LiveData.bindNotNull(context, block)`方法的实现，如果value无变化，不会重复调用`block`方法
> **注意**，以上两个方法所接收的Context必须是FragmentActivity一类的`LifecycleOwner`，否则绑定无法生效

## 具体用法

#### 如果需要自定义绑定LiveData到View属性
```kotlin
val liveData = "Hello".live

textView().apply {
    // 绑定liveData响应到TextView的text属性
    liveData.bindNotNull(context) { text = it }
}

// textView的文案将响应以下变化
liveData.data = "Hello BrickUI"
```

**Comment by guozhiqiang123** [comment]
这样做也可以，我最开始的考虑是把所有View的属性都封装到UIState中，这样只需要创建一个对象就能管理所有属性的监听和更新。你这种bind的方式每一个属性就需要创建一个LiveData对象（需要动态能力的属性），总感觉有一丢丢浪费。

**Comment by robin8yeung** [comment]
> 

不需要每个属性都创建LIveData，可以借助LiveData.map()，LiveData.combine()等扩展函数。参考以下示例：

```kotlin
val userInfo = UserInfo("Bob", 18).live

liveText(
    text = userInfo.map { it.name }
)
liveText(
    text = userInfo.map { it.age }
)
```

**Comment by guozhiqiang123** [comment]
我说的属性是View的属性，比如我现在要动态更改textview的gravity属性，就需要用livedata把gravity包裹，如果所有属性都需要动态，那不就是每一个属性都需要livedata包裹吗？不过你给出示例可以按需bind，倒也是可以接受的。
