### ISSUE TITLE
一些劝说话语

### ISSUE THREAD

**Issue by Onion99** [robin8yeung/BrickUI#4]
说实话,android 不缺声明式UI的轮子,像[Anko](https://github.com/Kotlin/anko)本身已经成熟了,只是不维护了,
后续的第三方继承者 [Splitties](https://github.com/LouisCAD/Splitties)实现上也大同小异,
再到Facebook的Litho和官方的JetpackCompose 性能问题也逐渐修好,后面很多人开发都会转到这了
话说还来当初还差点加入你们团队了,可惜路途遥远没去了 😃😃

**Comment by robin8yeung** [comment]
前面3个我了解了下，Litho还是挺强的，不过学起来和写起来还是挺有门槛的。Compose确实是Jetbrain一直在持续优化和推广的，也确实是个趋势，现在感觉对于基本使用，性能问题不大了，光是有IDE支持这一点是其他任何一个都无法比拟的，毕竟想快速上手，没什么比一个可以直接点击查看的layout指示器更方便的。学习和写Compose的门槛也不算高，但是一个项目接入Compose还是有一定门槛的，比如主题，颜色这些东西都另起炉灶了。当然Compose还有跨平台的优势，但感觉实际用起来没有flutter方便，但是flutter的性能又不太行。

当然，这些看法也可能是我先入为主了~

哈哈，下次有缘还可以继续关注我们团队~

**Comment by lihe6666** [comment]
我是个小白，也是过来学习的。首先我很佩服作者，有想法，有能力！做的很棒。
其次，我想表达我的看法，我是用了一段时间Jetpack Compose，很好用。我前几年一直不敢入android的坑就是xml太NM恶心了，但现在用Jetpack Compose 最起码我能写出一个app了，Compose就是原生，xml也是，我看官方说明这两个可以自由切换，是没有太多成本和代价的。

再说，这个项目能坚持多久。我就怕突然说 因为作者精力有限， 放弃了。

**Comment by robin8yeung** [comment]
> 我是个小白，也是过来学习的。首先我很佩服作者，有想法，有能力！做的很棒。 其次，我想表达我的看法，我是用了一段时间Jetpack Compose，很好用。我前几年一直不敢入android的坑就是xml太NM恶心了，但现在用Jetpack Compose 最起码我能写出一个app了，Compose就是原生，xml也是，我看官方说明这两个可以自由切换，是没有太多成本和代价的。
> 
> 再说，这个项目能坚持多久。我就怕突然说 因为作者精力有限， 放弃了。

Compose确实已经很棒，不过我自己实际接触了一些，感觉切换起来也不是毫无成本的，貌似主题、颜色这些是不能直接用传统xml那些。再者kotlin出了那么久，也还是有不少项目仍然在用java。所以我觉得也不矛盾吧。

至于说项目维护的问题，其实现在BrickUI已经是个总体可用的状态了，而不是像其他一些类似项目那样是个半成品，我自己也把它用在一些实际上线的功能中，或者一些需要快速实现的demo中。

此外这个项目也算是一种尝试或者一种思路吧，作为一个个人项目，也不可能期望去挑战官方框架或者其他团队框架。

**Comment by lihe6666** [comment]
嗯嗯，给你个大大的赞。

确实在主题方面我没有太深入，那块挺麻烦的。希望你能继续坚持，我也要向你学习！
