### ISSUE TITLE
让IDE帮我们处理一些工作

### ISSUE THREAD

**Issue by guozhiqiang123** [robin8yeung/BrickUI#5]
期望加上@ColorInt @ColorRes这些类型注解，让IDE帮我们判断类型。
![image](https://github.com/robin8yeung/BrickUI/assets/20378988/f341a600-7a72-475b-95e0-f8be74d77973)

**Comment by robin8yeung** [comment]
最近几天在外地，可能周三左右才能处理~

**Comment by guozhiqiang123** [comment]
> 最近几天在外地，可能周三左右才能处理~

不着急，我只是写一些demo遇到了问题。

**Comment by robin8yeung** [comment]
[release] 0.2.22

- improve: 为资源相关扩展函数添加类型注解
- improve: RecyclerView,SmartRefresh等添加Receiver为Context的扩展函数
