### ISSUE TITLE
使用smartRefresh有崩溃

### ISSUE THREAD

**Issue by guozhiqiang123** [robin8yeung/BrickUI#7]
smartRefresh直接套liveSimpleRecyclerView会崩溃
![image](https://github.com/robin8yeung/BrickUI/assets/20378988/e25d5404-f057-45da-9e60-92200442f808)
崩溃信息如下:
![image](https://github.com/robin8yeung/BrickUI/assets/20378988/1f4e8bb8-0098-43e4-960b-dce6fc8f5f73)

另外smartRefresh在Context下没有扩展函数，使用的时候必须外层套一个其他的ViewGrop,希望能提供一下，如图一。

**Comment by guozhiqiang123** [comment]
原因应该是如下图，进行了多次addView操作
![image](https://github.com/robin8yeung/BrickUI/assets/20378988/69ab66e8-d64b-494c-b19a-ad118cf91c7f)

**Comment by guozhiqiang123** [comment]
我提了个PR，已经解决这个问题了，是因为直接调用了ViewGroup作用域下的方法，导致多次addView

**Comment by robin8yeung** [comment]
[release] 0.2.22

- improve: 为资源相关扩展函数添加类型注解
- improve: RecyclerView,SmartRefresh等添加Receiver为Context的扩展函数

另外我看PR的改动范围有点超预期，我还是先自己改了，先不合这个PR了
