### ISSUE TITLE
scrollview的bug

### ISSUE THREAD

**Issue by guozhiqiang123** [robin8yeung/BrickUI#9]
![截图_选择区域_20231101135914](https://github.com/robin8yeung/BrickUI/assets/20378988/44af8d9d-379f-476c-9323-4c33882efd02)
形如这样的布局，当edittext不断输入换行，会把顶上的view一起往上顶。
如果写成xml或者直接addview的方式加入ScrollView就没有这个问题，我猜测是使用的ScrollView的构造函数不同，导致丢失了某些默认设置。
直接addView如下面这样是没有问题的：
![截图_选择区域_20231101140244](https://github.com/robin8yeung/BrickUI/assets/20378988/39d41888-6166-4421-b5a5-06f2514e980d)

另外如edittext等这些特殊控件特有的常用属性，希望能直接提供，比如edittext的行高设置，比如recyclerview的clipToPadding等

**Comment by robin8yeung** [comment]
我复现了下，应该只是输入法把整个Activity顶起来了，根节点的Column没有什么可滚动的特性，不可能把顶上的view往上顶的，Activity中加个 window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_NOTHING) 就不会了。
对于行高，如果应用中用得比较少，建议仍然用apply；如果用得比较多，建议放到style里，形成统一的一系列文本样式，也方便复用；clipToPadding这种，一般项目里用得也比较少，还是建议使用apply了。
